# Generated by Django 2.1.4 on 2018-12-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtergroup',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.FilterGroup'),
        ),
    ]
