# Generated by Django 2.1.4 on 2018-12-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181222_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtergroup',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='filteritem',
            old_name='status',
            new_name='is_active',
        ),
    ]
