# Generated by Django 2.1.4 on 2018-12-26 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_filtergroup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.TextField()),
                ('content', models.TextField()),
                ('full_content', models.TextField()),
                ('user_name', models.TextField()),
                ('user_image_url', models.TextField()),
                ('user_description', models.TextField()),
                ('polarity', models.FloatField()),
                ('subjectivity', models.FloatField()),
                ('retweet_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('user_location', models.TextField()),
                ('coordnates', models.TextField()),
                ('geo_location', models.TextField()),
                ('screen_name', models.TextField()),
                ('user_followers_count', models.IntegerField()),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
