# Generated by Django 2.1.4 on 2018-12-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_followers_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
