# Generated by Django 2.1.4 on 2018-12-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181226_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_followers_count',
            field=models.BigIntegerField(),
        ),
    ]
