# Generated by Django 2.1.4 on 2018-12-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181227_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='coordnates',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='geo_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_location',
            field=models.TextField(null=True),
        ),
    ]
